2018-07-31 12:43:44,026 - root - DEBUG - p.12 --->  /Users/reed.feldman/Desktop/symphonyPythonClient/resources/certificates/bot.user11.p12
2018-07-31 12:43:44,034 - root - DEBUG - Auth/authenticate() --> needed to authenticate
2018-07-31 12:43:44,034 - root - DEBUG - Auth/get_session_token()
2018-07-31 12:43:44,811 - root - DEBUG - Auth/get_keyauth()
2018-07-31 12:43:45,992 - root - DEBUG - DataFeedClient/createDatafeed()
2018-07-31 12:43:48,530 - root - DEBUG - DataFeedClient/readDatafeed()
2018-07-31 12:44:18,975 - root - DEBUG - no data coming in from datafeed --> readDatafeed()
2018-07-31 12:44:18,975 - root - DEBUG - DataFeedClient/readDatafeed()
